### ISSUE TITLE
Invalid salt version: 2

### ISSUE THREAD

**Issue by markau** [felixrieseberg/Ghost-Azure#1]
The deployment went perfectly - thank you!.  When navigating to /ghost/settings (for initial config) and clicking save, I got the error "Invalid salt version: 2" [screenshot](http://i.imgur.com/WO44opY.png?1).  

Subsequently navigating to /ghost/settings/ redirects to /ghost/signin/ where entering username and password again throws the error "Invalid salt version: 2".

**Comment by markau** [comment]
Well, I deleted the Azure Web App and repeated the process, and it worked this time. I suppose I will close the issue. Thank you.

**Comment by felixrieseberg** [comment]
Thanks for reporting though! I have to admit that I have no idea what happened (I guess something inside bcrypt), but I'll ignore this one for now :)

**Comment by vvianyy** [comment]
It happens here:  Invalid salt version: 2

**Comment by ErisDS** [comment]
I just discovered the underlying cause of this error. There was a bit of code in Ghost that was missed during a refactor, meaning the second char of the password hash was being stored instead of the whole hash. 

This particular piece of code only gets executed if something else goes wrong though! It only happens in the exact case that you try to setup your blog and the 'owner user' fixture is not in place in the users table. This means in the case of an older blog that a previous migration must have failed to complete successfully, or in the case of a new blog, that the fixtures were not populated properly on the first run.

I am not sure if there is anything about the Azure environment which may cause fixture population to fail more than on other environments, so thought I'd flag up this explanation here just in case.

The password hashing bug will be fixed in the next version of Ghost (0.7).

Note this explanation is only true for the exact error 'Invalid salt version: 2' when trying to setup a Ghost blog.
