### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by rushfrisby** [felixrieseberg/Ghost-Azure#28]
Got to the Deployment Complete step on deploy.azure.com. Waited a "solid minute" which has turned into an hour, and I'm still getting a blank web page. Actually its a 500 response with no content:

> HTTP/1.1 500 Internal Server Error
> Content-Length: 0
> Server: Microsoft-IIS/8.0
> X-Powered-By: ASP.NET
> Date: Wed, 20 Apr 2016 04:55:15 GMT

Deploying to a Basic-small instance. Any ideas as to why?

**Comment by MarkMasiak** [comment]
Did you use the Azure template from the old management portal to install ghost, or did you use the deploy to azure form GitHub?

I found the Azure template didn’t work – i’ve contacted azure support but they didn’t give a sh*t 

The GitHub deployment works but does take a while to deploy, then you need to go to domainname/ghost

 https://azuredeploy.net/

If you deployed from Github you should have a [Deployments] tab in the azure management portal if you don’t – delete ghost and install from Git Hub for Felix Rieseberg deployment

Also on the azure portal (old version) on the config tab 
Scroll down to 
Deployments section (should contain information)
App settings section (where you configure some variables such as URL & mail settings)
Also set:
    Always On – ON
    Web Sockets – ON
    Platform – 64BIT
    Managed Pipeline mode – INTEGRATED
    PHP – 5.6
Otherwise the site goes to sleep and you need to restart it and wait 2 min for everything to kick in

**Comment by rushfrisby** [comment]
I deployed from GitHub using the Deploy to Azure button. I tried from both the felixrieseberg repo and the AzureWebApps fork with no luck. I have a deployments tab in the management portal:

![image](https://cloud.githubusercontent.com/assets/574729/14674062/e5ca26ac-06cf-11e6-83b2-b4adaeee68de.png)

The other settings are as you mentioned. [https://rushghostblog.azurewebsites.net/](https://rushghostblog.azurewebsites.net/) is still coming up with a 500 error.

I'll try a fresh deploy this morning.

**Comment by fboucher** [comment]
I got the same problem last weekend. Didn't have the time to investigate. I use the Ghost template from Azure Marketplace :( that one worked.

**Comment by felixrieseberg** [comment]
Hey everyone, quick update: We upgraded the Ghost repo here to Node v4, which seems to fix a sqlite issue that I'm sure some of you ran into. It should work fine for you now!

**Comment by rushfrisby** [comment]
That must have fixed it. The deploy to Azure button is working now. Thanks @felixrieseberg

**Comment by felixrieseberg** [comment]
Thanks for testing! Im going to be super bold and close this is issue, but if there's something else going on, feel free to reopen or to open a new issue!
