### ISSUE TITLE
Preserving URL rewriting with auto deploy

### ISSUE THREAD

**Issue by RyanONeill1970** [felixrieseberg/Ghost-Azure#40]
I deploy from the main GitHub source repo and I'd like to keep the rewrites I have in web.config.

They are for rewriting www prefixes to the root domain.

Would it be possible to reference a rewrite.config file that from the web.config which is kept out of source control? This could then be created on the initial deploy. I could then keep my rewrites on upgrades.

It would break for existing upgraders though.

Your thoughts?

**Comment by TerribleDev** [comment]
couldn't you just simply fork the repo, add your commits, and then whenever there are new changes to pull down just rebase.

**Comment by RyanONeill1970** [comment]
I could (having not done a rebase, I think I could). Thank you.

**Comment by TerribleDev** [comment]
I recently switched over to hexo from ghost, but when I ran ghost I ran it off this repo. That is exactly what I would do. I had a ton of stuff such as web.config's custom themes, and what not. Basically I had a bunch of commits, and whenever this repo changed I would just rebase the changes. Since I was not editing files created by this repo I never had any conflicts or anything.
